[package]
name = "ipc"
version = "0.1.0"
edition = "2021"

[features]
default = ["pretty_errors"]
pretty_errors = ["format_serde_error"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_repr = "0.1"
format_serde_error = { version = "0.3", optional = true }
